[package]
name = "digital_rain"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.13.0"
bevy = "0.14.2"
once_cell = "1.20.2"
rand = "0.8.5"
tokio = { version = "1.41.1", features = ["full"] }
